import { useTheme } from "next-themes";
import Head from "next/head";
import { SyntheticEvent, useEffect, useRef, useState } from "react";
import ArrowDownSvg from "../components/ArrowDownSvg";
import ArrowUpSvg from "../components/ArrowUpSvg";
import MoonSvg from "../components/MoonSvg";
import SunSvg from "../components/SunSvg";
import { inquisitor } from "../library/fake";
import fetcher from "../library/fetcher";

type Run = { text: string; problem: boolean };

export default function Home() {
	const [selectedFile, setSelectedFile] = useState<File>();
	const { theme, setTheme } = useTheme();

	const [report, setReport] = useState<Run[]>([
		{ text: inquisitor, problem: false },
		{ text: "yabadaba", problem: false },
		{ text: "doo\n", problem: true },
		{ text: "nabayaba", problem: false },
		{ text: "doo", problem: true },
	]);

	const [positions, setPositions] = useState<number[]>([]);

	async function handleSubmit() {
		setPositions([]);
		setReport([]);
		const res = await fetcher<Run[]>("/fake", "PUT", selectedFile);
		if ("message" in res) {
			alert(res.message);
			setReport([{ text: res.message, problem: true }]);
		} else {
			setReport(res);
		}
	}

	function scrollTo(dir: "up" | "down") {
		// alert(dir);
		const currY = window.scrollY;
		let nextY: number;

		if (dir === "up") {
			nextY = positions.find((pos, i) => positions[i + 1] > currY) || currY;
		} else {
			nextY = positions.find((pos) => pos > currY) || currY;
		}

		window.scrollTo({ top: nextY });
	}

	function handleLoadProblem(e: SyntheticEvent<HTMLSpanElement>) {
		console.log("load problem");
		const rect = e.currentTarget.getBoundingClientRect();
		const position = rect.top || rect.y;
		setPositions((pre) => [...pre, position]);
	}

	useEffect(() => {
		console.log(positions);
	}, [positions]);

	return (
		<div className="w-full h-full">
			<Head>
				<meta name="description" content="Generated by create next app" />
				<meta property="og:title" content="Tonal Distancing" />
				<meta property="og:description" content="Tonal Distancing" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<aside className="flex flex-col items-center m-4">
				<form onSubmit={handleSubmit} className="flex flex-col items-center">
					<label className="invisible" htmlFor="fileinput">
						Upload File
					</label>
					<input
						id="fileinput"
						name="fileinput"
						type="file"
						// value={selectedFile}
						onChange={(e) => {
							if (e.target.files) {
								setSelectedFile(e.target.files[0]);
							}
						}}
						className="file:border-0 file:bg-dune-green dark:file:bg-drac-green dark:file:text-drac-black file:text-dune-white file:rounded-full hover:file:underline file:p-3 file:font-bold file:opacity-90 hover:file:opacity-100 transition-opacity file:w-full file:cursor-pointer"
					/>

					<p className="mt-6">{selectedFile?.name}</p>
					<label htmlFor="submit" className="invisible">
						Submit
					</label>
					<input
						type="submit"
						id="submit"
						name="submit"
						className="block 
								bg-dune-blue dark:bg-drac-purple dark:text-drac-black 
								border-0 opacity-90 hover:opacity-100 transition-opacity 
								font-sans font-bold p-3 px-4 rounded-full w-full 
								hover:underline cursor-pointer"
					/>
				</form>
			</aside>
			<main className="z-10 flex flex-col items-center w-full">
				<div className="max-w-[75ch] text-2xl text-justify">
					{Boolean(report)
						? report.map((run) => (
								<span
									className={`my-2 whitespace-pre-line font-serif text-justify
										dark:selection:bg-drac-white
										${run.problem ? "text-dune-red dark:text-drac-red problem" : "text-dune-grey dark:text-drac-white"}
										`}
									key={run.text.slice(0, 10)}
									onLoad={run.problem ? (e) => handleLoadProblem(e) : undefined}
								>
									{run.text}
								</span>
						  ))
						: "aoh wfawohf\nawohf\naowhe foaeh foa;wf haweiohf awoiefh\nawoe;f eoifh eofih eiofh eoifh ;oifh wo;ifh\na;oiefh ao;wefih\nawo;efh aw;oiefh aweoi;hf"}
				</div>
			</main>
			<button
				onClick={() => setTheme(theme === "light" ? "dark" : "light")}
				className="w-8 h-8 fixed bottom-8 right-8 z-10 hover:scale-125 transition-transform"
			>
				{theme === "light" ? <SunSvg /> : <MoonSvg />}
			</button>

			{Boolean(report) && (
				<div className="flex flex-col items-center fixed bottom-8 left-8">
					<button
						className="block w-8 h-8 hover:scale-125 transition-transform"
						onClick={() => scrollTo("up")}
					>
						<ArrowUpSvg />
					</button>
					<button
						className="block w-8 h-8 hover:scale-125 transition-transform"
						onClick={() => scrollTo("down")}
					>
						<ArrowDownSvg />
					</button>
				</div>
			)}
		</div>
	);
}
